# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3'

services:

  orderer.property-registration-network.com:
    container_name: orderer.property-registration-network.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/property-registration-network.com/orderers/orderer.property-registration-network.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/property-registration-network.com/orderers/orderer.property-registration-network.com/tls/:/var/hyperledger/orderer/tls
        - orderer.property-registration-network.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.registrar.property-registration-network.com:
    container_name: peer0.registrar.property-registration-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.registrar.property-registration-network.com
      - CORE_PEER_ADDRESS=peer0.registrar.property-registration-network.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.registrar.property-registration-network.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.registrar.property-registration-network.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.registrar.property-registration-network.com:7051
      - CORE_PEER_LOCALMSPID=registrarMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/registrar.property-registration-network.com/peers/peer0.registrar.property-registration-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/registrar.property-registration-network.com/peers/peer0.registrar.property-registration-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.registrar.property-registration-network.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.registrar.property-registration-network.com:
    container_name: peer1.registrar.property-registration-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.registrar.property-registration-network.com
      - CORE_PEER_ADDRESS=peer1.registrar.property-registration-network.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.registrar.property-registration-network.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.registrar.property-registration-network.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.registrar.property-registration-network.com:7051
      - CORE_PEER_LOCALMSPID=registrarMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/registrar.property-registration-network.com/peers/peer1.registrar.property-registration-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/registrar.property-registration-network.com/peers/peer1.registrar.property-registration-network.com/tls:/etc/hyperledger/fabric/tls
        - peer1.registrar.property-registration-network.com:/var/hyperledger/production

    ports:
      - 8051:8051

  peer0.users.property-registration-network.com:
    container_name: peer0.users.property-registration-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.users.property-registration-network.com
      - CORE_PEER_ADDRESS=peer0.users.property-registration-network.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.users.property-registration-network.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.users.property-registration-network.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.users.property-registration-network.com:10051 peer2.users.property-registration-network.com:11051
      - CORE_PEER_LOCALMSPID=usersMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/users.property-registration-network.com/peers/peer0.users.property-registration-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/users.property-registration-network.com/peers/peer0.users.property-registration-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.users.property-registration-network.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.users.property-registration-network.com:
    container_name: peer1.users.property-registration-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.users.property-registration-network.com
      - CORE_PEER_ADDRESS=peer1.users.property-registration-network.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.users.property-registration-network.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.users.property-registration-network.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.users.property-registration-network.com:11051 peer0.users.property-registration-network.com:9051
      - CORE_PEER_LOCALMSPID=usersMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/users.property-registration-network.com/peers/peer1.users.property-registration-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/users.property-registration-network.com/peers/peer1.users.property-registration-network.com/tls:/etc/hyperledger/fabric/tls
        - peer1.users.property-registration-network.com:/var/hyperledger/production
    ports:
      - 10051:10051

  peer2.users.property-registration-network.com:
    container_name: peer2.users.property-registration-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2.users.property-registration-network.com
      - CORE_PEER_ADDRESS=peer2.users.property-registration-network.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer2.users.property-registration-network.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.users.property-registration-network.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.users.property-registration-network.com:9051 peer1.users.property-registration-network.com:10051
      - CORE_PEER_LOCALMSPID=usersMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/users.property-registration-network.com/peers/peer2.users.property-registration-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/users.property-registration-network.com/peers/peer2.users.property-registration-network.com/tls:/etc/hyperledger/fabric/tls
        - peer2.users.property-registration-network.com:/var/hyperledger/production
    ports:
      - 11051:11051
