# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3'

volumes:
  orderer.pharma-network.com:
  peer0.manufacturer.pharma-network.com:
  peer1.manufacturer.pharma-network.com:
  peer0.distributor.pharma-network.com:
  peer1.distributor.pharma-network.com:
  peer0.retailer.pharma-network.com:
  peer1.retailer.pharma-network.com:
  peer0.consumer.pharma-network.com:
  peer1.consumer.pharma-network.com:
  peer0.transporter.pharma-network.com:
  peer1.transporter.pharma-network.com:

networks:
  pharma-network:
  
services:
  orderer.pharma-network.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.pharma-network.com
    container_name: orderer.pharma-network.com
    networks:
      - pharma-network

  peer0.manufacturer.pharma-network.com:
    container_name: peer0.manufacturer.pharma-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.manufacturer.pharma-network.com
    networks:
      - pharma-network

  peer1.manufacturer.pharma-network.com:
    container_name: peer1.manufacturer.pharma-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.manufacturer.pharma-network.com
    networks:
      - pharma-network

  peer0.distributor.pharma-network.com:
    container_name: peer0.distributor.pharma-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.distributor.pharma-network.com
    networks:
      - pharma-network

  peer1.distributor.pharma-network.com:
    container_name: peer1.distributor.pharma-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.distributor.pharma-network.com
    networks:
      - pharma-network

  peer0.retailer.pharma-network.com:
    container_name: peer0.retailer.pharma-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.retailer.pharma-network.com
    networks:
      - pharma-network

  peer1.retailer.pharma-network.com:
    container_name: peer1.retailer.pharma-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.retailer.pharma-network.com
    networks:
      - pharma-network

  peer0.consumer.pharma-network.com:
    container_name: peer0.consumer.pharma-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.consumer.pharma-network.com
    networks:
      - pharma-network

  peer1.consumer.pharma-network.com:
    container_name: peer1.consumer.pharma-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.consumer.pharma-network.com
    networks:
      - pharma-network

  peer0.transporter.pharma-network.com:
    container_name: peer0.transporter.pharma-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.transporter.pharma-network.com
    networks:
      - pharma-network

  peer1.transporter.pharma-network.com:
    container_name: peer1.transporter.pharma-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.transporter.pharma-network.com
    networks:
      - pharma-network

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_VM_ENDPOINT=http://192.168.56.1:2375
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.manufacturer.pharma-network.com:7051
      - CORE_PEER_LOCALMSPID=manufacturerMSP
      - CORE_PEER_TLS_ENABLED=true
#      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/manufacturer.pharma-network.com/peers/peer0.manufacturer.pharma-network.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/manufacturer.pharma-network.com/peers/peer0.manufacturer.pharma-network.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/manufacturer.pharma-network.com/peers/peer0.manufacturer.pharma-network.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/manufacturer.pharma-network.com/users/Admin@manufacturer.pharma-network.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.pharma-network.com
      - peer0.manufacturer.pharma-network.com
      - peer1.manufacturer.pharma-network.com
      - peer0.distributor.pharma-network.com
      - peer1.distributor.pharma-network.com
      - peer0.retailer.pharma-network.com
      - peer1.retailer.pharma-network.com
      - peer0.consumer.pharma-network.com
      - peer1.consumer.pharma-network.com
      - peer0.transporter.pharma-network.com
      - peer1.transporter.pharma-network.com
    networks:
      - pharma-network

  # chaincode:
  #   container_name: chaincode
  #   image: hyperledger/fabric-ccenv:$IMAGE_TAG
  #   tty: true
  #   environment:
  #     - GOPATH=/opt/gopath
  #     - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
  #     - FABRIC_LOGGING_SPEC=INFO
  #     - CORE_PEER_ID=chaincode
  #     - CORE_PEER_ADDRESS=peer0.manufacturer.pharma-network.com:7051
  #     - CORE_PEER_LOCALMSPID=manufacturerMSP
  #     - CORE_PEER_TLS_ENABLED=false
  #     - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/crypto/peerOrganizations/manufacturer.pharma-network.com/users/Admin@manufacturer.pharma-network.com/msp
  #     - CORE_TLS_CLIENT_KEY_PATH=/opt/gopath/src/crypto/peerOrganizations/manufacturer.pharma-network.com/users/Admin@manufacturer.pharma-network.com/tls/client.key
  #     - CORE_TLS_CLIENT_CERT_PATH=/opt/gopath/src/crypto/peerOrganizations/manufacturer.pharma-network.com/users/Admin@manufacturer.pharma-network.com/tls/client.crt
  #     - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/crypto/peerOrganizations/manufacturer.pharma-network.com/users/Admin@manufacturer.pharma-network.com/tls/ca.crt
  #   working_dir: /opt/gopath/src/chaincode
  #   command: /bin/bash -c 'sleep 6000000'
  #   volumes:
  #     - /var/run/:/host/var/run/
  #     - ./../chaincode/node:/opt/gopath/src/chaincode
  #    # - ./../chaincode-advanced:/opt/gopath/src/chaincode-advanced
  #     - ./crypto-config:/opt/gopath/src/crypto
  #   networks:
  #     - pharma-network
